name: Matrix Build with Artifacts

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build (Matrix)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [14, 16, 18]   # 3 variants for Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: matrix-07514bc
        run: echo "Building for Node.js version ${{ matrix.version }}"

      - name: Generate build artifact
        run: echo "Build output for Node.js version ${{ matrix.version }}" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-07514bc-v${{ matrix.version }}
          path: output.txt